name: Tests

on: [push, pull_request]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ruby and Bundle Install
        uses: ruby/setup-ruby@v1

        with:
          bundler-cache: true

      - name: Specs
        env:
          CI: true
          COVERAGE: true
          MINIMUM_COVERAGE: 80

        run: bundle exec rspec spec

      - name: Coverage Report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

        uses: codecov/codecov-action@v3
